apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
spec:
  selector:
    app: rest-app
  ports:
    - protocol: TCP
      port: 8080       # Port exposed on the cluster network
      targetPort: 8080 # Port the application container is listening on
  type: ClusterIP      # Internal cluster routing; we will port-forward this to localhost